bash phenotype_qc.sh platelet_count_phen_and_covars.txt platelet_count ../samples/AFR_unrelated_samples.txt AFR_norm_platelet_count_phen_covars.txt
bash phenotype_qc.sh platelet_count_phen_and_covars.txt platelet_count ../samples/EUR_unrelated_samples.txt EUR_norm_platelet_count_phen_covars.txt
